import jsPDF from "jspdf";

interface PdfRow {
  label: string;
  value: string;
  bold?: boolean;
}

interface PdfSection {
  title: string;
  rows: PdfRow[];
}

interface PdfExportOptions {
  reportTitle: string;
  subtitle?: string;
  sections: PdfSection[];
  footer?: string;
}

export const generatePDF = ({ reportTitle, subtitle, sections, footer }: PdfExportOptions) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Brand header bar
  doc.setFillColor(13, 36, 64); // brand-navy
  doc.rect(0, 0, pageWidth, 40, "F");

  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("ASTROMAR LOGISTICS PVT LTD", pageWidth / 2, 16, { align: "center" });

  // Report title
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(reportTitle, pageWidth / 2, 26, { align: "center" });

  // Tagline
  doc.setFontSize(8);
  doc.setTextColor(180, 200, 220);
  doc.text("Seamless Innovation. Unmatched Reliability.", pageWidth / 2, 34, { align: "center" });

  y = 50;

  // Subtitle / date
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}`, 14, y);
  if (subtitle) {
    doc.text(subtitle, pageWidth - 14, y, { align: "right" });
  }
  y += 10;

  // Sections
  sections.forEach((section) => {
    // Check page break
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // Section title
    doc.setFillColor(240, 244, 248);
    doc.rect(14, y - 5, pageWidth - 28, 9, "F");
    doc.setTextColor(13, 36, 64);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(section.title, 18, y + 1);
    y += 12;

    // Rows
    section.rows.forEach((row) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(9);
      if (row.bold) {
        doc.setFont("helvetica", "bold");
        doc.setTextColor(13, 36, 64);
      } else {
        doc.setFont("helvetica", "normal");
        doc.setTextColor(60, 60, 60);
      }
      doc.text(row.label, 18, y);

      doc.setFont("helvetica", "bold");
      doc.setTextColor(13, 36, 64);
      doc.text(row.value, pageWidth - 18, y, { align: "right" });

      // Separator line
      doc.setDrawColor(230, 230, 230);
      doc.line(18, y + 2, pageWidth - 18, y + 2);
      y += 7;
    });

    y += 6;
  });

  // Footer
  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  y += 5;
  doc.setDrawColor(13, 36, 64);
  doc.setLineWidth(0.5);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(footer || "This report is generated by Astromar Logistics Tools — a product of Astromar Logistics Pvt Ltd.", 14, y);
  y += 5;
  doc.text("For accurate quotations, contact us at www.astromarlogistics.com", 14, y);
  y += 5;
  doc.text("Disclaimer: Calculations are estimates based on standard industry formulas. Actual costs may vary.", 14, y);

  // Powered by
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text("Powered by Astromar Logistics Tools | Astromar Logistics Pvt Ltd | www.astromarlogistics.com", pageWidth / 2, footerY, { align: "center" });

  return doc;
};

export const downloadPDF = (options: PdfExportOptions, filename: string) => {
  const doc = generatePDF(options);
  doc.save(filename);
};
